# Generated by Django 4.2.11 on 2024-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
